name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  lint-and-test:
    name: 'Lint & Test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.0.2
          run_install: true

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Installing Deps
        run: |
          pnpm install

      - name: Lint
        run: |
          pnpm run lint

      - name: Test
        run: |
          pnpm test
